# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IssueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("TRUCK", "Truck"),
                            ("WORKSHOP", "Workshop"),
                            ("BREAKDOWN", "Breakdown"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("issue_date", models.DateField()),
                ("remark", models.TextField(blank=True)),
            ],
            options={
                "db_table": "issue_items",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SPARE_PART", "Spare Part"),
                            ("TYRE", "Tyre"),
                            ("MATERIAL", "Material"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pcs", help_text="e.g. pcs, litres, kg", max_length=30
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("STORE", "Store"),
                            ("WORKSHOP", "Workshop"),
                            ("BREAKDOWN", "Breakdown"),
                        ],
                        max_length=15,
                    ),
                ),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_applicable", models.BooleanField(default=False)),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField()),
                ("remark", models.TextField(blank=True)),
            ],
            options={
                "db_table": "purchases",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening Balance"),
                            ("PURCHASE", "Purchase"),
                            ("ISSUE", "Issue"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("vat_applicable", models.BooleanField(default=False)),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.BigIntegerField(blank=True, null=True)),
                ("remark", models.TextField(blank=True)),
            ],
            options={
                "db_table": "stock_ledger",
                "ordering": ["-created_at"],
            },
        ),
    ]
