# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trucks", "0001_initial"),
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_ledger_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="ledger_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase",
                to="inventory.stockledger",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.location"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="core.supplier",
            ),
        ),
        migrations.AddField(
            model_name="issueitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="issueitem",
            name="ledger_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue",
                to="inventory.stockledger",
            ),
        ),
        migrations.AddField(
            model_name="issueitem",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.location"
            ),
        ),
        migrations.AddField(
            model_name="issueitem",
            name="truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="trucks.truck",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["item", "location", "created_at"],
                name="stock_ledge_item_id_dcc061_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="stock_ledge_transac_43e99a_idx",
            ),
        ),
    ]
