# Generated by Django 4.2.7 on 2026-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("SPARE_PART", "Spare Part"),
                    ("TYRE", "Tyre"),
                    ("MATERIAL", "Material"),
                    ("LUBRICANT", "Lubricant"),
                ],
                max_length=15,
            ),
        ),
    ]
