# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_limit",
                    models.DecimalField(
                        decimal_places=2, help_text="Max litres per fill", max_digits=8
                    ),
                ),
            ],
            options={
                "db_table": "fuel_limits",
            },
        ),
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("litres", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fuel_limit", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "excess_fuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "price_per_litre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "odometer",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                ("remark", models.TextField(blank=True)),
            ],
            options={
                "db_table": "fuel_logs",
                "ordering": ["-date"],
            },
        ),
    ]
