# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trucks", "0001_initial"),
        ("fuel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuellog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fuellog",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuel_logs",
                to="trips.trip",
            ),
        ),
        migrations.AddField(
            model_name="fuellog",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fuel_logs",
                to="trucks.truck",
            ),
        ),
        migrations.AddField(
            model_name="fuellimit",
            name="truck",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_limit",
                to="trucks.truck",
            ),
        ),
    ]
