[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
REACT_APP_API_URL = "https://taurus-logistics-production-0a15.up.railway.app/api"

[start]
cmd = "npx serve -s build -p ${PORT:-3000}"
