[phases.setup]
nixPkgs = ["python311", "libmysqlclient"]

[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py migrate", "python manage.py shell -c \"from django.contrib.auth import get_user_model; U = get_user_model(); U.objects.filter(email='admin@taurus.com').exists() or U.objects.create_superuser('admin@taurus.com', 'admin1234')\""]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
