# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("truck_number", models.CharField(max_length=20, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("chassis_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "inactive_reason",
                    models.TextField(
                        blank=True, help_text="Mandatory when status is INACTIVE"
                    ),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("dvla_expiry", models.DateField(blank=True, null=True)),
                ("fitness_expiry", models.DateField(blank=True, null=True)),
                ("permit_expiry", models.DateField(blank=True, null=True)),
                ("vit_last_paid_date", models.DateField(blank=True, null=True)),
                ("vit_next_due_date", models.DateField(blank=True, null=True)),
                (
                    "current_odometer",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "trucks",
                "ordering": ["truck_number"],
            },
        ),
        migrations.CreateModel(
            name="TruckDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="trucks/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="trucks.truck",
                    ),
                ),
            ],
            options={
                "db_table": "truck_documents",
            },
        ),
    ]
