# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trucks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tyre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=30)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STORE", "In Store"),
                            ("FITTED", "Fitted"),
                            ("WORKSHOP", "Workshop"),
                            ("CONDEMNED", "Condemned"),
                        ],
                        default="STORE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "tyres",
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="TyreAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(max_length=10)),
                ("fitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "odometer_fit",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "odometer_remove",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "km_used",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                ("removal_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "tyre_assignments",
                "ordering": ["-fitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TyreSwap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_position", models.CharField(max_length=10)),
                ("to_position", models.CharField(blank=True, max_length=10)),
                ("swap_date", models.DateField()),
                ("odometer", models.DecimalField(decimal_places=1, max_digits=10)),
                ("remarks", models.TextField(blank=True)),
                (
                    "from_truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="swaps_from",
                        to="trucks.truck",
                    ),
                ),
            ],
            options={
                "db_table": "tyre_swaps",
                "ordering": ["-swap_date"],
            },
        ),
    ]
