# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("tyres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trucks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tyreswap",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tyreswap",
            name="to_truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="swaps_to",
                to="trucks.truck",
            ),
        ),
        migrations.AddField(
            model_name="tyreswap",
            name="tyre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="swaps",
                to="tyres.tyre",
            ),
        ),
        migrations.AddField(
            model_name="tyreassignment",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tyre_assignments",
                to="trucks.truck",
            ),
        ),
        migrations.AddField(
            model_name="tyreassignment",
            name="tyre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="tyres.tyre",
            ),
        ),
        migrations.AddField(
            model_name="tyre",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.item",
            ),
        ),
    ]
