# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TYRE", "Tyre"),
                            ("SPARE_PART", "Spare Part"),
                            ("DRIVER_WAGE", "Driver Wage"),
                            ("TOLL", "Toll"),
                            ("ADMIN", "Admin"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="finance/receipts/"
                    ),
                ),
            ],
            options={
                "db_table": "expenditures",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("HAULAGE", "Haulage"), ("OTHER", "Other")],
                        default="HAULAGE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "revenues",
                "ordering": ["-date"],
            },
        ),
    ]
