# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                (
                    "ghana_card_no",
                    models.CharField(
                        help_text="GHA-XXXXXXXXX-X", max_length=20, unique=True
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("licence_number", models.CharField(max_length=50, unique=True)),
                ("licence_class", models.CharField(default="C", max_length=10)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("licence_expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("RESIGNED", "Resigned"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "drivers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="drivers/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_documents",
            },
        ),
    ]
