# Generated by Django 4.2.7 on 2026-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("waybill_no", models.CharField(max_length=50, unique=True)),
                ("origin", models.CharField(max_length=150)),
                ("destination", models.CharField(max_length=150)),
                ("material_type", models.CharField(max_length=100)),
                ("loaded_qty", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "delivered_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "qty_difference",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("loading_time", models.DateTimeField()),
                ("unloading_time", models.DateTimeField(blank=True, null=True)),
                ("trip_duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("EN_ROUTE", "En Route"),
                            ("DELAYED", "Delayed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=10,
                    ),
                ),
                (
                    "rate_per_ton",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "trip_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("remark", models.TextField(blank=True)),
            ],
            options={
                "db_table": "trips",
                "ordering": ["-loading_time"],
            },
        ),
    ]
